/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    FunctionPanel: typeof import('./src/components/FunctionPanel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconComponent: typeof import('./src/components/base/IconComponent.vue')['default']
    IconPonent: typeof import('./src/components/IconPonent.vue')['default']
    InterfacePanel: typeof import('./src/components/InterfacePanel.vue')['default']
    ZSplitter: typeof import('./src/components/base/ZSplitter.vue')['default']
    ZSplitterPanel: typeof import('./src/components/base/ZSplitterPanel.vue')['default']
  }
}
