/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    FunctionPanel: typeof import('./src/components/FunctionPanel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconComponent: typeof import('./src/components/base/IconComponent.vue')['default']
    InterfacePanel: typeof import('./src/components/InterfacePanel.vue')['default']
    RequestItem: typeof import('./src/components/RequestItem.vue')['default']
    RequestPanel: typeof import('./src/components/RequestPanel.vue')['default']
    TPanel: typeof import('./src/components/TPanel.vue')['default']
    ZParamTable: typeof import('./src/components/base/ZParamTable.vue')['default']
    ZSplitter: typeof import('./src/components/base/ZSplitter.vue')['default']
    ZSplitterPanel: typeof import('./src/components/base/ZSplitterPanel.vue')['default']
    ZTabPane: typeof import('./src/components/base/ZTabPane.vue')['default']
    ZTabs: typeof import('./src/components/base/ZTabs.vue')['default']
    ZVariableInput: typeof import('./src/components/base/ZVariableInput.vue')['default']
  }
}
